### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by domoritz** [potassco/asprin#1]
I would love to use asprin with Python 3. I think the main thing that would need to be fixed are imports: https://docs.python.org/3/reference/import.html. Ideally, asprin would also be compatible with https://anaconda.org/potassco/clingo so that it's really easy to install and use it.

**Comment by javier-romero** [comment]
That's a good point! I will do that once I find the time.

**Comment by javier-romero** [comment]
I found the time :)

**Comment by domoritz** [comment]
Nice! Congrats on the release.
