### ISSUE TITLE
Error with --meta=query (due to simplification?)

### ISSUE THREAD

**Issue by alviano** [potassco/asprin#11]
Hi! 

We run in the following issue when trying to use the --meta=query option (instance simplified to the best of our possibilities):

```
$ cat bug.asprin
#preference(p1, subset){a}.
#optimize(p1).

{a}.
b :- a.
b :- b.

$ asprin bug.asprin --meta=query
asprin version 3.1.1
Reading from bug.asprin
*** ERROR: (asprin): 'int' object is not iterable
UNKNOWN

$ clingo --version
clingo version 5.4.0
Address model: 64-bit

libclingo version 5.4.0
Configuration: with Python 3.8.5, without Lua

libclasp version 3.3.5 (libpotassco version 1.1.0)
Configuration: WITH_THREADS=1
Copyright (C) Benjamin Kaufmann

License: The MIT License <https://opensource.org/licenses/MIT>
```

My feeling is that the issue is due to the simplification of the rule "b :- b." (which in our original program was produced by a rewriting script and was including other body literals).

Changing the atoms in the preference does no difference.
Adding defining rules for query/1 does no difference.
Removing any of those rules or the --meta=query option would not trigger the issue.

Hope it may help.

All the best,
Mario and Carmine

**Comment by javier-romero** [comment]
Thank you Mario and Carmine, I'll have a look!

**Comment by javier-romero** [comment]
Hi, I just fixed it, please let me know if the issue remains in the real instance.

And also let me know if you manage to solve any instance using that option :)
In a previous version of asprin I had implemented different approaches to solve that task more efficiently (see Section 3.1 of [1]), but that implementation is not part of the current version of the system (I just pushed the work in progress branch).

[1] Javier Romero, Torsten Schaub, Philipp Wanko: Computing Diverse Optimal Stable Models. [ICLP (Technical Communications) 2016: 3:1-3:14
